###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.6"
networks:
  default:
    name: symfony-demo.local

services:
    postgres:
      image: postgres:11.1-alpine
      container_name: symfony-demo-postgres
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=symfony-demo

    webserver:
      image: nginx:alpine
      container_name: symfony-demo-webserver
      working_dir: /app
      volumes:
          - ./:/app
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    php:
      build: phpdocker/php-fpm
      container_name: symfony-demo-php
      working_dir: /app
      volumes:
        - ./:/app
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

